import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faWallet,
  faCogs,
  faChevronDown,
  faArrowLeft,
  faPlus,
  faTrashAlt,
  faCheckCircle,
  faPen,
  faSignOutAlt,
  faCopy,
  faLayerGroup,
  faUserFriends,
  faTimes,
  faRetweet,
  faDollarSign,
} from '@fortawesome/free-solid-svg-icons';

library.add(
  faWallet,
  faCogs,
  faChevronDown,
  faArrowLeft,
  faPlus,
  faTrashAlt,
  faCheckCircle,
  faPen,
  faSignOutAlt,
  faCopy,
  faLayerGroup,
  faUserFriends,
  faTimes,
  faRetweet,
  faDollarSign,
);
